### ISSUE TITLE
Comparison graph colors

### ISSUE THREAD

**Issue by Royalphax** [AsyncDevTeam/mcMMO-Stats-Panel#10]
When comparing 2 players, graph areas have the same color (and different colors for each ability). One color for player 1 and one color for player 2 should be enough ?

![image](https://github.com/AsyncDevTeam/mcMMO-Dashboard/assets/13496987/ae34a254-22a7-4b06-ac2f-9fe71b7464cf)

**Comment by NicolasVaillant** [comment]
I think this chart sucks.
There's only 1 background color for radar. It's hard to see differences between players.

Let's try another chart type.
