### ISSUE TITLE
Horizontal scroll bar - LeaderBoard and Best Player

### ISSUE THREAD

**Issue by veteranmina** [AsyncDevTeam/mcMMO-Stats-Panel#14]
Players have noticed when viewing on pc the horizontal scroll bar can be difficult to navigate with while others didn't know it was available in the leaderboard.

Can the scrollbar width be increased ever so slightly or click-drag be available for table views?

Thank you!

**Comment by NicolasVaillant** [comment]
Hi @veteranmina, thank you for opening an issue! Your contribution is much appreciated.

The table should already be draggable... Unfortunately, that's a bug.

**Comment by NicolasVaillant** [comment]
I addressed the issue for the table to make it draggable. And I chose to set the top leaderboard on two columns. Thank you for reporting it! Join our Discord server to help us improve the dashboard.
