### ISSUE TITLE
Best/Worst verbiage - Neutral terms

### ISSUE THREAD

**Issue by veteranmina** [AsyncDevTeam/mcMMO-Stats-Panel#15]
Could the verbiage for this be configurable or changed to be 'more neutral' towards players?

Different verbiage ie Top and Newest would work as neutral words.

**Comment by NicolasVaillant** [comment]
Thank you for your review.
I'm not sure I clearly understand your request. 

Would you like to set these tags to be more neutral? If yes, you can change them with "labels_user" in parameters.js.

<img width="935" alt="image" src="https://github.com/AsyncDevTeam/mcMMO-Dashboard/assets/77850354/45b8d31a-c320-45b1-8e80-bc380ec55380">
