### ISSUE TITLE
I have Issue after installation and configuration

### ISSUE THREAD

**Issue by PatalkokGIT** [AsyncDevTeam/mcMMO-Stats-Panel#16]
Hello,

the JSON error code :

An error occured at fLoadServerInfos (https://www.spiral-buddies.fr/resources/js/shared.js:229:9): Unexpected end of JSON input, lang:EN, settings:{"force_darkMode":false,"animated_skins":false,"localStorage":false,"refreshStorage":"h","version":"1.30.1"}

link : https://www.spiral-buddies.fr

**Comment by NicolasVaillant** [comment]
Hey @PatalkokGIT, 
It seems to be a bad config of the `config/config.php` file. It's always a bad config... ^^

BUT

When accessing your file on the server, I get an internal server error. I can't even get more details... 
Have you changed the following file `resources/php/scripts/get_server_stats.php` by any chance?

I have other dashboards running 1.30.1 without any problems that's weird.
