### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by arturek1666** [AsyncDevTeam/mcMMO-Stats-Panel#17]
An error occured at fLoadServerInfos (https://fanimc.pl/mcmmo/resources/js/shared.js:229:9): Unexpected token 'W', "
Warning: i"... is not valid JSON, lang:EN, settings:{"force_darkMode":false,"animated_skins":false,"localStorage":false,"refreshStorage":"h","version":"1.30.1"}

The only thing I did was added mysql in config. I try to redo it but still no luck have all the supported PHP etc.

**Comment by NicolasVaillant** [comment]
Hello @arturek1666,
Sorry for my delayed response.

mcMMO-Dashboard is showing an "access denied" message for your database. Please refer to our [FAQ](https://mcmmo.nicolasvaillant.net/pages/faq.html) for assistance.

Check your PHP version and credentials. If the error persists, reach out to us on our [Discord](https://discord.com/invite/TFeEzCP4e5), and I will investigate your issue.
