### ISSUE TITLE
"By Abilities" chart data is incorrect

### ISSUE THREAD

**Issue by xStellarZ** [AsyncDevTeam/mcMMO-Stats-Panel#5]
The values in the line chart are "shifted"; for example, it shows Axes as the highest skill, whereas in the pie chart you can see that those values represent Mining rather than Axes. None of them have the correct values. I have not altered anything other than basic config.
![line_chart](https://user-images.githubusercontent.com/75229701/235392250-5e311f31-33fa-4eba-a958-b264ba233b5a.png)
![pie_chart](https://user-images.githubusercontent.com/75229701/235392260-2f3f30d3-fea7-4737-9c98-63ad626bee12.png)

**Comment by xStellarZ** [comment]
@Royalphax @NicolasVaillant reminder to please help me take a look at this, I love this dashboard and would like it to work properly so that I can leave a good rating! Thank you

**Comment by NicolasVaillant** [comment]
I'll take a quick look at your problem. Thank you for your comment!
