### ISSUE TITLE
Expose the skin URL services to support username and uuid.

### ISSUE THREAD

**Issue by Legoman99573** [AsyncDevTeam/mcMMO-Stats-Panel#6]
This would be beneficial for servers that have geysermc installed to support Bedrock players as they go through a different skin service that will render both Java and Bedrock players.

Documentation here: https://tydiumcraft.net/docs/skinapi

**Comment by NicolasVaillant** [comment]
Hi @Legoman99573! I'm glad to tell you that we now support Bedrock skins in v.1.23.0.

Please join our [Discord server](https://discord.gg/TFeEzCP4e5) to share your experience with the community.
